runtime: nodejs20 

env_variables:
  PORT: "8080"
  MONGODB_URI: "mongodb+srv://cutu:aditicutu123@cluster0.wpzcv6s.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET: "yartsy_app_jwt_secret_2025"
  ARTSY_CLIENT_ID: "20492ff48442c910dc09"
  ARTSY_CLIENT_SECRET: "a41f03bab3279f4fa90eeb19ee4cdd66"
  NODE_ENV: "production"